name: Benchmark (Criterium)

on:
  workflow_dispatch:

jobs:
  benchmark:
    name: Run benchmark
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Java
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Set up Clojure
        uses: DeLaGuardo/setup-clojure@13.2
        with:
          cli: latest

      - name: Cache Clojure dependencies
        uses: actions/cache@v4
        with:
          path: |
            ~/.m2
            ~/.gitlibs
            ~/.clojure/.cpcache
          key: ${{ runner.os }}-clojure-${{ hashFiles('deps.edn') }}
          restore-keys: |
            ${{ runner.os }}-clojure-

      - name: Pre-download project dependencies
        run: clojure -P

      - name: Run benchmark
        run: clojure -M:benchmark
